version: "3.3"

services:
  mirror-primary:
    container_name: mirror-primary
    build:
      context: .
      dockerfile: Dockerfile
    env_file: secret.env
    volumes:
      - /mnt/storage/mirror:/mirror
    restart: "unless-stopped"
